# Generated by Django 3.0.3 on 2020-02-29 14:32

from django.db import migrations
import phonenumbers


def normalize_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        regular_phonenum = flat.owners_phonenumber
        parsed_phonenum = phonenumbers.parse(regular_phonenum, "RU")
        flat.owner_phone_pure = phonenumbers.format_number(parsed_phonenum, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owner_phone_pure'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumber)
    ]
