# Generated by Django 3.0.3 on 2020-02-29 15:47

from django.db import migrations


def reverse_previous(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_phone_pure = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20200229_1732'),
    ]

    operations = [
        migrations.RunPython(reverse_previous)
    ]
