# Generated by Django 3.0.3 on 2020-02-29 15:55

from django.db import migrations
import phonenumbers


def normalize_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        regular_phonenum = flat.owners_phonenumber
        parsed_phonenum = phonenumbers.parse(regular_phonenum, "RU")
        flat.owner_phone_pure = phonenumbers.format_number(parsed_phonenum, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
        flat.save()


def reverse_previous(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_phone_pure = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20200229_1847'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumber, reverse_previous)
    ]



