# Generated by Django 3.0.3 on 2020-03-01 07:05

from django.db import migrations


def fill_owner_card(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner, owners_phonenumber=flat.owners_phonenumber, owner_phone_pure=flat.owner_phone_pure)


def reverse_filling(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20200229_1951'),
    ]

    operations = [
        migrations.RunPython(fill_owner_card, reverse_filling)
    ]
