# Generated by Django 3.0.3 on 2020-03-01 17:23

from django.db import migrations


def add_flat_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        the_flat_owner, created = Owner.objects.get_or_create(owner=flat.owner, owners_phonenumber=flat.owners_phonenumber)
        the_flat_owner.owned_property.add(flat)


def reverse_adding(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flat = ''


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20200301_2023'),
    ]

    operations = [
        migrations.RunPython(add_flat_to_owner, reverse_adding)
    ]
